### ISSUE TITLE
Generate qid used directly into biocache for downloads

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#1]
Already present.

@adam-collins: Should be easy to add extra line to point layer metadata pop-up that reports qid: Adam has done this.

**Comment by nickdos** [comment]
Lee: Given current authentication differences, a pull from BCCVL using a qid is expedient; a push won't work without shared authenctication. Add option to SP point layer metadata pop-up that provides the qid (Adam wortking on now). User logs into BCCVL and there should be an import option to enter a qid. Alternative is download from SP, upload to BCCVL.

**Comment by nickdos** [comment]
Should be easy to add extra line to point layer metadata pop-up that reports qid: Adam has done this.

**Comment by Tasilee** [comment]
Yes, and it checks out nicely. Regardless of what's happening at the BCCvL end, it may be worth adding the url for the table view and download as a visual demonstration of why the qid. Users will tend to click the links and ignore the link url.
