### ISSUE TITLE
Investigate privacy concerns

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#11]
Investigate privacy concerns with email address in download requests.

**Comment by gweis** [comment]
Seems to be no problem as this should be covered by our terms of use.

**Comment by rp-ala** [comment]
See links:
From ALA terms of use: http://www.ala.org.au/about-the-atlas/terms-of-use/#pi
The ALA privacy policy: http://www.ala.org.au/about-the-atlas/terms-of-use/privacy-policy/

**Comment by ysliaw01** [comment]
May need to update the BCCVL's term of use to say that their email may be sent to ALA when they download dataset from ALA (or other external link) for identification purpose??

**Comment by nickdos** [comment]
You may also need to refer the user to ALA's T&C's as they are effectively using the ALA.

**Comment by ysliaw01** [comment]
BCCVL privacy policy: http://www.bccvl.org.au/about/legal/privacy-policy/

The BCCVL's privacy policy has already covered the use of personal info.

"Griffith may use third parties service-providers to provide functionality associated with the BCCVL. Consequently, Your name, Your contact details and Your employing Institution may be given to such third parties – but only for the provision of services associated with the BCCVL. If You upload datasets into the BCCVL, You will also be asked to insert basic contact information which may constitute Personal Information."
