### ISSUE TITLE
Add source type breakdowns in logger

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#13]
- incorporating report into dashboard - Then add breakdown by source type to dashboard.
- adding extra report to logger - investigate whether an extra breakdown report needs adding to logger system.

**Comment by nickdos** [comment]
Logger is an old app and who ever does this task will require some ramp-up time to learn the system. Dashboard changes is a separate but dependent issue

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/26a764df4048d416621e97e336eadd44a2c3c35e
https://github.com/AtlasOfLivingAustralia/dashboard/commit/821607afa715cdb34e520f2c70cc0cd4ff7f343c
https://github.com/AtlasOfLivingAustralia/logger-service/commit/188c107210f5fe3d64b808a3b98fd1cf288f15cf
