### ISSUE TITLE
Add callback url parameter for POSTing topmost point layer in SP

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#2]
> Decide best presentation, relates to data BCCVL uploads to sandbox

I'm not sure what this means... can someone elaborate?

**Comment by adam-collins** [comment]
1. SP will accept a speciesCallbackUrl parameter.
2. SP will POST to the speciesCallbackUrl a JSON list of [name, qid, biocache-service url] every time the topmost species layer in the layer list changes.

**Comment by adam-collins** [comment]
no longer required
