### ISSUE TITLE
Add Export | BCCVL menu to SP

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#4]
See this use case: issue #23

**Comment by adam-collins** [comment]
Not sure what this issue is about. 

I thought it might be about creating a help doc page about how to clean the data. The help would also include instructions on how to get the qid into other applications, e.g. BCCVL

?

**Comment by Tasilee** [comment]
I'm presuming that this simply means cleaning the data in the Spatial Portal and making it available in projects such as BCCvL.

The cleaning process is as per workshops I have been running and I will load it up after latest update to a case study.

**Comment by nickdos** [comment]
What Lee said... I'm not sure this is an actual issue or simply a inferred benefit for round tripping from BCCVL to ALA (**to SP to remove outliers via click and exclude**) and then back to BCCVL. As the bolded text is already available in the SP...

**Comment by adam-collins** [comment]
Clicking on the export to BCCVL button will require:
1. save SP session
2. create url to return to the SP session and include an extra parameter to prompt SP to fetch the BCCVL callback url.
3. on returning from BCCVL login success, do a GET call to BCCVL to fetch the callback url.
4. POST the species layer selection from within export BCCVL option to the callback url.

**Comment by adam-collins** [comment]
For purposes for testing the POST to BCCVL, a functional spatial-portal Export | Export to BCCVL is available. This is a direct link that will start the process http://sandbox-test.ala.org.au/webportal//?q=data_resource_uid:drt13038&dynamic=true&ws=http://sandbox-test.ala.org.au/ala-hub&bs=http://sandbox-test.ala.org.au/biocache-service&tool=exportspeciesexternal

**Comment by adam-collins** [comment]
New test url http://sandbox-test.ala.org.au/webportal//?q=data_resource_uid:drt13038&dynamic=true&ws=http://sandbox-test.ala.org.au/ala-hub&bs=http://sandbox-test.ala.org.au/biocache-service

https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/d5244aefe587af8b324a40e62a870743f2a613fa
https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/00328bfd32e7e47c3f8d1b6fa10e665bdef4de72
https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/592173e72603da1255662ebcc9fab7c957c23fc5
https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/0bae1f3dd20e178e4ebd649dd6e775e4c1121933
https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/0507d98fbb9dd7091f2c7779250e55d8b54af740
