### ISSUE TITLE
Add BCCVL logo within ALA at data transfer point/s for cross-branding, and vice versa ALA logo in BCCVL at transfer points.

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/ecological-science#40]

**Comment by gweis** [comment]
Is there a specific logo we should include here? (I'll check with our UI/UX people regarding size)

**Comment by rp-ala** [comment]
I'll link in our comms people who can provide ALA logos.

**Comment by patkyn** [comment]
Passed ALA logo to BCCVL and BCCVL team has passed the logo to ALA team.
