### ISSUE TITLE
Add callback url parameter to POST uploaded layer info to BCCVL

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#8]
> ALA to provide a web service/URL to allow BCCVL to send a user-uploaded data set to SP with data going into sandbox. assumes [agreed format of CSV data (headers)](../issues/7).

Can someone comment on how this will be used by BCCVL? E.g. is it for data cleaning (outlier removal, names matching, etc), followed by generating a QID to be used back in BCCVL to automatically download the cleaned data for use in a subsequent modelling experiment?

**Comment by Tasilee** [comment]
Currently, BCCvL use minimal columns (lat and long) but they need to handle more with multi-species modelling and trait modelling so STRONGLY suggest they adopt explicit darwinCore terms as headers, then one would hope the Sandbox would have an easy time.

**Comment by nickdos** [comment]
I've added issue #23 which might be useful background info.

**Comment by adam-collins** [comment]
Instead of supplying the URLs as parameters, the BCCVL URLs are set in the spatial-portal properties file. https://github.com/AtlasOfLivingAustralia/spatial-portal/commit/d5244aefe587af8b324a40e62a870743f2a613fa
