### ISSUE TITLE
Research possible authentication methods for BCCVL-ALA requests

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ecological-science#9]
It would be nice if a BCCVL users didn't have to authenticate in both systems when sending data from BCCVL to ALA (see #23). This issue is to look into possible security models for passing the data securely between the 2 organisations. 

E.g. one possibility is for BCCVL to have an API key that it sends in the request header (over https) that marks it as a trusted source. And then the email address is used to identify the user's data. Or we hook into CAS and treat BCCVL a bit like we allow FB and Google logins.

**Comment by patkyn** [comment]
BCCVL will send apiKey in request header over https. 

Not all BBCVL users login via AAF, therefore hooking up AAF to CAS is not a viable solution at this point
